
services:
  traefik:

    image: traefik:v2.10
    container_name: "traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.http.routers.traefik.service=traefik-svc"
      - "traefik.http.services.traefik-svc.loadbalancer.server.port=8080"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  connexion:
    image: marcosf2/dragon-core
    build:
      context: ./dragon-core
    container_name: "dragon-core"
    environment:
      COMPOSE_PROJECT_NAME: dev
      TRAEFIK_HOST: kaladin.ncsa.illinois.edu
      VOLUME_ORIGIN: ./pytest/tmp
      LAIRS_DIRECTORY: .
      RESOURCE_PATH: .
      USERS: '["Smaug", "Spyro", "Drogon", "Charizard"]'
      API_URL_PREFIX: http://kaladin.ncsa.illinois.edu
      URL_HOST: http://kaladin.ncsa.illinois.edu
      CREATE_TESTING_ENVIRONMENT: True

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.connexion.rule=Host(`labdragon.software.ncsa.Illinois.edu`) && PathPrefix(`/api`)"
      - "traefik.http.services.connexion.loadbalancer.server.port=8000"


  nextjs:
    image: marcosf2/dragon-scales
    container_name: "dragon-scales"
    build:
      context: ./dragon-scales
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`labdragon.software.ncsa.Illinois.edu`)"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"

networks:
  monitor:
    driver: bridge
    ipam:
      driver: default
      config:
        -  subnet: 192.168.1.0/24
    driver_opts:
      com.docker.network.driver.mtu: 1450
