# IQUIST/NCSA
# UIUC

[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "Entity"
version = "0.1"
inherits_from = "object"  # Can also be a list for multiple inheritance

# FIXME: How do I represent the comments structure? Since I do want to just accept a list of comments with the metadata being handled automatically.
#  How do you specify that?
[definitions]
# Fields that need to be satisfied alongside their data structures
# Must be either imported classes or primitive types.
ID = "Optional[str]"
name = "str"
previous_names = "List[str]"
parent = "Union[str, Path]"
user = "str"
deleted = "bool"
description = "str"
comments = "List[Union[Comment, Table, str]]"
children = "List[Union[str, Path]]"
params = "List[Tuple[str]]"
data_buckets = "List[Union[str, Path]]"
bookmarked = "bool"
start_time = "str"
end_time = "str"

# Imports is optional
[imports]
#Param = "components.Parameter"


[defaults]
# Default values for each of the fields
ID = "None"
name = ''
previous_names = []
parent = ''
deleted = "False"
description = ''
comments = []
children = []
params= []
data_buckets = []
bookmarked = "False"
start_time = ""
end_time = ""

# Params is optional
[params]

[properties]
linkable = "maybe"
structured = "maybe"
nested = "maybe"
process = "maybe"
storage = "maybe"
versioned = "maybe"
timestamped = "maybe"