# IQUIST/NCSA
# UIUC

[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "Entity"
version = "0.1"
inherits_from = "object"  # Can also be a list for multiple inheritance

[definition]
# Fields that need to be satisfied alongside their data structures
# Must be either imported classes or primitive types.
ID = "UUID"
name = "str"
parent_link = "UUID"
parent_class = "str"
user = "str"
description = "str"
comments = "List[UUID]"
related_links = "List[UUID]"
params = "List[Tuple[str]]"

# Imports is optional
[imports]
#Param = "parameters.Parameter"


[defaults]
# Default values for each of the fields
ID = ''
name = ''
parent_link = ''
parent_class = ''
user = ''
description = ''
comments = []
related_links = []
params= []

# Params is optional
[params]

[properties]
linkable = "maybe"
structured = "maybe"
nested = "maybe"
process = "maybe"
storage = "maybe"
versioned = "maybe"
timestamped = "maybe"