# IQUIST/NCSA
# UIUC

[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "Entity"
version = "0.1"
inherits_from = "object"  # Can also be a list for multiple inheritance

[definitions]
# Fields that need to be satisfied alongside their data structures
# Must be either imported classes or primitive types.
ID = "Optional[str]"
name = "str"
parent = "Union[str, Path]"
user = "str"
description = "str"
comments = "List[str]"
children = "List[Union[str, Path]]"
params = "List[Tuple[str]]"

# Imports is optional
[imports]
#Param = "parameters.Parameter"


[defaults]
# Default values for each of the fields
ID = "None"
name = ''
parent = ''
user = ''
description = ''
comments = []
children = []
params= []

# Params is optional
[params]

[properties]
linkable = "maybe"
structured = "maybe"
nested = "maybe"
process = "maybe"
storage = "maybe"
versioned = "maybe"
timestamped = "maybe"