# IQUIST/NCSA
# UIUC

[annotations]
organization = "IQUIST/NCSA"
name = "Instance"
version = "0.1"
inherits_from = "Entity"

[definitions]
start_time = "str"
end_time = "str"
version = "int"
stored_params = "Union[List[Path], List[str]]"
tags = "List[str]"
images = "Union[List[Path], List[str]]"
data = "Union[List[Path], List[str]]"
data_structure = "Dict[str, Union[Tuple[int], int]]"
analysis = "Union[List[Path], List[str]]"

[defaults]
start_time = ""
end_time = ""
version = 0
stored_params = ""
tags = ""
images = []
data = []
data_structure = {}
analysis = []

[imports]
Path = "from pathlib import Path"

[properties]
linkable = "yes"
structured = "no"
nested = "not"
process = "no"
storage = "yes"
versioned = "yes"
timestamped = "yes"