# IQUIST/NCSA
# UIUC

[annotations]
organization = "IQUIST/NCSA"
name = "Instance"
version = "0.1"
inherits_from = "Entity"

[definitions]
parent_class = "Optional[Entity]"
start_time = "str"
end_time = "str"
version = "int"
stored_content = "List[Path]"

[defaults]
start_time = ""
end_time = ""
version = 0
stored_content = ""
parent_class = "None"

[imports]
Path = "from pathlib import Path"

[properties]
linkable = "yes"
structured = "no"
nested = "not"
process = "no"
storage = "yes"
versioned = "yes"
timestamped = "yes"