# IQUIST/NCSA
# UIUC

[annotations]
organization = "IQUIST/NCSA"
name = "instance"
version = "0.1"

[definition]
inherits_from = ["entity"]

[definition.fields]
start_time = "timestamp"
end_time = "timestamp"
version = "value"
stored_content = "path"

[defaults.fields]
start_time = 0
end_time = 0
version = 0
stored_content = ""

[properties]
linkable = "yes"
structured = "no"
nested = "not"
process = "no"
storage = "yes"
versioned = "yes"
timestamped = "yes"