# IQUIST/NCSA
# UIUC

[annotations]
organization = "IQUIST/NCSA"
name = "Project"
version = "0.1"
inherits_from = "Entity"

[definitions]

[defaults]

[properties]
linkable = "yes"
structured = "no"
nested = "yes"
process = "no"
storage = "no"
versioned = "no"
timestamped = "no"