# IQUIST/NCSA
# UIUC

[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "Step"
version = "0.1"
inherits_from = "Entity"

[definitions]
process = "str"


[defaults]
process=""

[properties]
linkable = "yes"
structured = "yes"
nested = "no"
process = "yes"
storage = "no"
versioned = "no"
timestamped = "yes"