# IQUIST/NCSA
# UIUC

[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "step"
version = "0.1"

[definition]
inherits_from = "entity"

[definition.fields]
start_time = "timestamp"
end_time = "timestamp"

[defaults.fields]
parent_class = "entity"
start_time = "timestamp"
end_time = "timestamp"

[properties]
linkable = "yes"
structured = "yes"
nested = "no"
process = "yes"
storage = "no"
versioned = "no"
timestamped = "yes"