# IQUIST/NCSA
# UIUC

[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "Step"
version = "0.1"
inherits_from = "Entity"

[definitions]
parent_class = "Optional[Entity]"
process = "str"
start_time = "timestamp"
end_time = "timestamp"


[defaults]
process=""
parent_class = "None"
start_time = ""
end_time = ""

[properties]
linkable = "yes"
structured = "yes"
nested = "no"
process = "yes"
storage = "no"
versioned = "no"
timestamped = "yes"