# IQUIST/NCSA
# UIUC

[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "task"
version = "0.1"


[definition]
inherits_from = "entity"

[definition.fields]
objective = "str"
start_time = "timestamp"
end_time = "timestamp"


[defaults.fields]
objective = ""
parent_class = "entity"
start_time = 0
end_time = 0

[properties]
linkable = "yes"
structured = "yes"
nested = "yes"
process = "yes"
storage = "no"
versioned = "no"
timestamped = "yes"