# IQUIST/NCSA
# UIUC

# Annotations are read-only fields.
[annotations]
# Information about the core elements of the entities
organization = "IQUIST/NCSA"
name = "Task"
version = "0.1"
inherits_from = "Entity"  # This is read only field.

[definitions] # Keys in the dictionary + the type

[defaults] # Default values for the keys

[properties] # Read only
linkable = "yes"
structured = "yes"
nested = "yes"
process = "yes"
storage = "no"
versioned = "no"
timestamped = "yes"